apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::565392451781:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-GUPK0NL0WVLW
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::565392451781:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-17T03:03:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1518"
  uid: fd68d625-a7a0-4e75-ab1b-d8717b22fbbe
